2024-12-23 10:40:26.911 [info] 




2024-12-23 10:40:26.933 [info] Extension host agent started.
2024-12-23 10:40:27.570 [info] [<unknown>][11a9acd2][ExtensionHostConnection] New connection established.
2024-12-23 10:40:27.579 [info] [<unknown>][ba8fd3fa][ManagementConnection] New connection established.
2024-12-23 10:40:27.675 [info] [<unknown>][11a9acd2][ExtensionHostConnection] <856> Launched Extension Host Process.
2024-12-23 10:40:41.845 [info] [<unknown>][ba8fd3fa][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
2024-12-23 10:40:41.878 [info] [<unknown>][11a9acd2][ExtensionHostConnection] <856> Extension Host Process exited with code: 0, signal: null.
2024-12-23 10:40:41.879 [info] Cancelling previous shutdown timeout
2024-12-23 10:40:41.879 [info] Last EH closed, waiting before shutting down
2024-12-23 10:40:53.211 [info] [<unknown>][296c2c93][ManagementConnection] New connection established.
2024-12-23 10:40:53.218 [info] [<unknown>][b5b87702][ExtensionHostConnection] New connection established.
2024-12-23 10:40:53.221 [info] [<unknown>][b5b87702][ExtensionHostConnection] <994> Launched Extension Host Process.
2024-12-23 10:45:41.881 [info] New EH opened, aborting shutdown
2024-12-23 10:45:41.884 [error] Error: Unexpected SIGPIPE
    at process.<anonymous> (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/server-main.js:184:1060)
    at process.emit (node:events:530:35)
2024-12-23 10:49:43.306 [info] [<unknown>][296c2c93][ManagementConnection] The client has reconnected.
2024-12-23 10:50:10.321 [info] [<unknown>][b5b87702][ExtensionHostConnection] The client has reconnected.
2024-12-23 10:54:45.688 [info] [<unknown>][296c2c93][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
2024-12-23 10:54:52.218 [info] [<unknown>][296c2c93][ManagementConnection] Another client has connected, will shorten the wait for reconnection 5m before disposing...
2024-12-23 10:54:52.218 [info] [<unknown>][296c2c93][ManagementConnection] The client has reconnected.
2024-12-23 10:54:53.595 [error] CodeExpectedError: Could not find pty 10 on pty host
    at I.W (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:48:12233)
    at I.updateIcon (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:48:7772)
    at N.s.<computed> (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:48:2962)
    at Object.call (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:31:4203)
    at Jc.s (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:29:78968)
    at Jc.q (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:29:78491)
    at us.value (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:29:77893)
    at C.B (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:29:746)
    at C.fire (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:29:964)
    at process.w (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:24:29142)
    at process.emit (node:events:518:28)
    at emit (node:internal/child_process:950:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2024-12-23 10:54:53.596 [error] CodeExpectedError: Could not find pty 10 on pty host
    at I.W (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:48:12233)
    at I.updateTitle (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:48:7722)
    at N.s.<computed> (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:48:2962)
    at Object.call (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:31:4203)
    at Jc.s (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:29:78968)
    at Jc.q (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:29:78491)
    at us.value (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:29:77893)
    at C.B (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:29:746)
    at C.fire (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:29:964)
    at process.w (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:24:29142)
    at process.emit (node:events:518:28)
    at emit (node:internal/child_process:950:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2024-12-23 10:54:53.596 [error] CodeExpectedError: Could not find pty 10 on pty host
    at I.W (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:48:12233)
    at I.updateTitle (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:48:7722)
    at N.s.<computed> (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:48:2962)
    at Object.call (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:31:4203)
    at Jc.s (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:29:78968)
    at Jc.q (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:29:78491)
    at us.value (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:29:77893)
    at C.B (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:29:746)
    at C.fire (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:29:964)
    at process.w (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:24:29142)
    at process.emit (node:events:518:28)
    at emit (node:internal/child_process:950:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2024-12-23 10:54:53.596 [error] CodeExpectedError: Could not find pty 10 on pty host
    at I.W (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:48:12233)
    at I.updateTitle (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:48:7722)
    at N.s.<computed> (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:48:2962)
    at Object.call (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:31:4203)
    at Jc.s (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:29:78968)
    at Jc.q (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:29:78491)
    at us.value (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:29:77893)
    at C.B (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:29:746)
    at C.fire (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:29:964)
    at process.w (file:///home/ubuntu/.vscode-server/cli/servers/Stable-fabdb6a30b49f79a7aba0f2ad9df9b399473380f/server/out/vs/platform/terminal/node/ptyHostMain.js:24:29142)
    at process.emit (node:events:518:28)
    at emit (node:internal/child_process:950:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2024-12-23 10:55:09.171 [info] [<unknown>][b5b87702][ExtensionHostConnection] The client has reconnected.
